package cz.cvut.fit.genepi.models;

import java.util.Date;

/**
 * UserDAO generated by hbm2java
 */
public class PatientDAO implements java.io.Serializable {

	/**
	 * generated serialVersionUID
	 */
	private static final long serialVersionUID = -8172690860460945951L;

	private int id;
	private String nin;
	private Date birthday;
	private String gender;
	private int doctorId;
	private int deleted;
	private int checked;
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNin() {
		return nin;
	}

	public void setNin(String nin) {
		this.nin = nin;
	}

	public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public int getDoctorId() {
		return doctorId;
	}

	public void setDoctorId(int doctorId) {
		this.doctorId = doctorId;
	}

	public int getDeleted() {
		return deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}

	public int getChecked() {
		return checked;
	}

	public void setChecked(int checked) {
		this.checked = checked;
	}

	public int getContactId() {
		return contactId;
	}

	public void setContactId(int contactId) {
		this.contactId = contactId;
	}

	public int getCommentId() {
		return commentId;
	}

	public void setCommentId(int commentId) {
		this.commentId = commentId;
	}

	private int contactId;
	private int commentId;

	public PatientDAO() {
	}

	public PatientDAO(int id, String nin, Date birthday, int doctorId,
			int deleted, int checked, int contactId, int commentId) {
		this.id = id;
		this.nin = nin;
		this.birthday = birthday;
		this.doctorId = doctorId;
		this.deleted = deleted;
		this.checked=checked;
		this.contactId = contactId;
		this.commentId = commentId;
	}

}