package cz.cvut.fit.genepi.models;
 
import java.util.Date;
 
// TODO: Auto-generated Javadoc
/**
 * UserDAO generated by hbm2java.
 */
public class UserDAO implements java.io.Serializable {
 
	/** generated serialVersionUID. */
	private static final long serialVersionUID = -6440259681541809279L;
	
	/** The user id. */
	private int userId;
	
	/** The username. */
	private String username;
	
	/** The created by. */
	private String createdBy;
	
	/** The created date. */
	private Date createdDate;
 
	/**
	 * Instantiates a new user dao.
	 */
	public UserDAO() {
	}
 
	/**
	 * Instantiates a new user dao.
	 *
	 * @param userId the user id
	 * @param username the username
	 * @param createdBy the created by
	 * @param createdDate the created date
	 */
	public UserDAO(int userId, String username, String createdBy,
			Date createdDate) {
		this.userId = userId;
		this.username = username;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}
 
	/**
	 * Gets the user id.
	 *
	 * @return the user id
	 */
	public int getUserId() {
		return this.userId;
	}
 
	/**
	 * Sets the user id.
	 *
	 * @param userId the new user id
	 */
	public void setUserId(int userId) {
		this.userId = userId;
	}
 
	/**
	 * Gets the username.
	 *
	 * @return the username
	 */
	public String getUsername() {
		return this.username;
	}
 
	/**
	 * Sets the username.
	 *
	 * @param username the new username
	 */
	public void setUsername(String username) {
		this.username = username;
	}
 
	/**
	 * Gets the created by.
	 *
	 * @return the created by
	 */
	public String getCreatedBy() {
		return this.createdBy;
	}
 
	/**
	 * Sets the created by.
	 *
	 * @param createdBy the new created by
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
 
	/**
	 * Gets the created date.
	 *
	 * @return the created date
	 */
	public Date getCreatedDate() {
		return this.createdDate;
	}
 
	/**
	 * Sets the created date.
	 *
	 * @param createdDate the new created date
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	} 
}