package cz.cvut.fit.genepi.models;
 
import java.util.Date;
 
/**
 * UserDAO generated by hbm2java
 */
public class UserDAO implements java.io.Serializable {
 
	/**
	 * generated serialVersionUID
	 */
	private static final long serialVersionUID = -6440259681541809279L;
	
	private int userId;
	private String username;
	private String createdBy;
	private Date createdDate;
 
	public UserDAO() {
	}
 
	public UserDAO(int userId, String username, String createdBy,
			Date createdDate) {
		this.userId = userId;
		this.username = username;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}
 
	public int getUserId() {
		return this.userId;
	}
 
	public void setUserId(int userId) {
		this.userId = userId;
	}
 
	public String getUsername() {
		return this.username;
	}
 
	public void setUsername(String username) {
		this.username = username;
	}
 
	public String getCreatedBy() {
		return this.createdBy;
	}
 
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
 
	public Date getCreatedDate() {
		return this.createdDate;
	}
 
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	} 
}